### ISSUE TITLE
Bot crashes if you delete the message quickly

### ISSUE THREAD

**Issue by EdyDeveloper** [kieranperk/CarterBot#3]
If you send the bot a message (DM or in a server channel) and then quickly delete it before the bot has a chance to answer, the node instance crashes.

**Comment by kieranperk** [comment]
This seems to be due to a bug where the bot passes the message that it has read into the reply function, and since it no longer exists it fails.

This should be fixed in the next bug patch!

**Comment by EdyDeveloper** [comment]
> This seems to be due to a bug where the bot passes the message that it has read into the reply function, and since it no longer exists it fails.
> 
> This should be fixed in the next bug patch!

Yea i noticed. Thanks for fixing it.

**Comment by kieranperk** [comment]
I'm closing this issue as, since carterapi is shutting down, I'm going to archive this repository.
